### PR TITLE
Malli example appveyor fix

### PR DESCRIPTION
**Pull request by dmg46664**
Please answer the following questions and leave the below in as part of your PR.

- [ ] I have read the [developer documentation](https://github.com/babashka/nbb/blob/main/doc/dev.md).

- [ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/nbb/blob/main/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] This PR contains a [test](https://github.com/babashka/nbb/blob/main/doc/dev.md#tests) to prevent against future regressions

- [ ] I have updated the [CHANGELOG.md](https://github.com/babashka/nbb/blob/main/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
Ah, this is actually an error in nbb itself. On Windows it should call `bb.exe` probably

**Comment by borkdude** [comment]
Also, I think we already had bb in appveyor, else we couldn't even run the tasks

**Comment by dmg46664** [comment]
@borkdude Ah, the suffix ".exe". I kick build, get up to something else and forget about it for an hour... repeat 😅

**Comment by dmg46664** [comment]
@borkdude In that case I'm going to close this and let you do it. You probably know where in the code to start looking and what else may need changing. I had originally thought that adding 'nbb.edn' had triggered something new, but as you say it's not the case.

**Comment by borkdude** [comment]
Thanks for the effort!

**Pull request closed without merging**
