### PR TITLE
Malli example docs updated

### PR DESCRIPTION
**Pull request by dmg46664**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/nbb/blob/main/doc/dev.md).

- [n/a] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/nbb/blob/main/doc/dev.md#start-with-an-issue-before-writing-code).

- [n/a ] This PR contains a [test](https://github.com/babashka/nbb/blob/main/doc/dev.md#tests) to prevent against future regressions

- [n/a] I have updated the [CHANGELOG.md](https://github.com/babashka/nbb/blob/main/CHANGELOG.md) file with a description of the addressed issue.

Per conversation https://clojurians.slack.com/archives/C029PTWD3HR/p1667383803311989

### CODE REVIEW

**Comment by dmg46664** [comment]
@borkdude oh, thought I'd try installing bb on appveyor (not entirely sure how it works).
But I see you've already merged it?

**Comment by borkdude** [comment]
Another PR for this is welcome. You can check clj-kondo appveyor.yml for this. Thanks!

**Comment by dmg46664** [comment]
@borkdude okay, but given that I need the build process to see if it has worked please can you leave it unmerged until it works 🙏

**Comment by borkdude** [comment]
Got it :) But CI was already broken before your PR, so I didn't expect you to fix it. Glad you're taking the time to do it.

**Pull request merged**
