### PR TITLE
Support downloading and installing dependencies via nbb.edn

### PR DESCRIPTION
**Pull request by lilactown**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/nbb/blob/main/doc/dev.md).
- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/nbb/blob/main/doc/dev.md#start-with-an-issue-before-writing-code).
- [x] This PR contains a [test](https://github.com/babashka/nbb/blob/main/doc/dev.md#tests) to prevent against future regressions
- [ ] I have updated the [CHANGELOG.md](https://github.com/babashka/nbb/blob/main/CHANGELOG.md) file with a description of the addressed issue.

---

This is a prototype of solving https://github.com/babashka/nbb/issues/20 by essentially encapsulating the guidance given in https://github.com/babashka/nbb/blob/51bf9dda0ee5392ce4b8f44054d6b8f4c5259ad4/doc/dependencies.md.

It adds the following capabilities to `nbb`:
- A new `--config` CLI arg which expects a deps.edn-like map as the following arg
- If `--config` is not passed, looks in the immediate local directory for an `nbb.edn` file, and if present reads it in as EDN

If a config map is available via the above methods, then does the following:
- Looks up `:deps` in the map loaded via the above methods, and hashes the value using `sha1` for caching purposes
- If `~/.nbb/_deps/*deps-hash*` doesn't exist yet, creates it and uses `bb` to download dependencies and create an uberjar. Extracts the uberjar to `~/.nbb/_deps/*deps-hash*/nbb-deps`
- Adds `~/.nbb/_deps/*deps-hash*/nbb-deps` to class path

Since you responded to https://github.com/babashka/nbb/issues/20#issuecomment-1193393740 saying that shelling out to `bb` is fine, the only thing I'm not sure about is the `~/.nbb/_deps` folder being where the jar is download to. I'm thinking I might change this to a local directory like `.nbb` or `.nbb-cache`. Thoughts?

### CODE REVIEW

**Comment by borkdude** [comment]
Great! Perhaps we can make the loading of the deps stuff also lazy, like all the rest in nbb? This is for faster startup when you don't use `nbb.edn`.

Yes, I think `.nbb/.cache` is more in line with e.g. `clj-kondo` which is `.clj-kondo/.cache` and downloading to the local dir seems fine when the script is ran from the current working directory and there is an node_modules directory already available.

**Comment by lilactown** [comment]
@borkdude can you help me understand what you mean by lazy? An example of where it's done elsewhere in the code would help.

If there's no `nbb.edn` present in the directory `nbb` is run in and you don't pass a map in via `--config`, it skips all the other steps. The only affect on startup time would be doing the `(fs/readdirSync ".")`. I could try some other methods to see if the file exists which might be faster.

**Comment by lilactown** [comment]
Just as a point-in-time example of the new functionality added in this PR:

```
$ node lib/nbb_main.js --config '{:deps {metosin/malli {:git/url "https://github.com/borkdude/malli" :git/sha "e400bbcdab09b21dc42d82f90400f60f85af6bd9"}}}' repl
Downloading dependencies...
Cloning: https://github.com/borkdude/malli
Checking out: https://github.com/borkdude/malli at e400bbcdab09b21dc42d82f90400f60f85af6bd9
Downloading: borkdude/dynaload/0.3.5/dynaload-0.3.5.pom from clojars
Downloading: borkdude/dynaload/0.3.5/dynaload-0.3.5.jar from clojars
Extracting dependencies...
Done.
Welcome to nbb v0.6.129!
user=> (require '[malli.core :as m])
nil
user=> %
$ node lib/nbb_main.js --config '{:deps {metosin/malli {:git/url "https://github.com/borkdude/malli" :git/sha "e400bbcdab09b21dc42d82f90400f60f85af6bd9"}}}' repl
Welcome to nbb v0.6.129!
user=> (require '[malli.core :as m])
nil
```

**Comment by borkdude** [comment]
What I mean is e.g. the bundle command only loads `bundle.mjs` when you execute the `nbb bundle` command.

**Comment by lilactown** [comment]
@borkdude thanks, I've updated the branch with those changes!

**Comment by eccentric-j** [comment]
This is great, thank you!

**Pull request merged**
