### PR TITLE
Add atom var

### PR DESCRIPTION
**Pull request by logseq-cldwalker**
Hi @borkdude. The motivation for adding this to nbb is I'd like to be able to check if something is an Atom e.g. `(instance? cljs.core/Atom state)`. While loading [this file](https://github.com/logseq/logseq/pull/10793/files#diff-7a301b7397e7f918dca1b572825d342e19d94f23911410dffaa233d81f752c2d) into nbb, this was the only cljs code that couldn't load normally. I didn't add a test since I didn't see any for just var additions but happy to do so if you'd like

---

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/nbb/blob/main/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/nbb/blob/main/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] This PR contains a [test](https://github.com/babashka/nbb/blob/main/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/nbb/blob/main/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
Can you add a test as well? It's not obvious that the instance check will succeed.

**Comment by logseq-cldwalker** [comment]
Sure. Added

**Comment by borkdude** [comment]
Thanks! I assume you don't need a new release since you build your own nbb-logseq right?

**Comment by logseq-cldwalker** [comment]
Yep! There's no rush for a new release

**Pull request merged**
